In [4]:
# Create a 1-dimensional array
import numpy as np
oneDarray = np.array([1,2,3])

oneDarray
oneDarray.ndim


1

In [5]:
array_1d = np.array([1, 2, 3, 4, 5])


print(array_1d)
print("Dimenstion: ",array_1d.ndim)


[1 2 3 4 5]
Dimenstion:  1


In [6]:
# Create a 2-dimensional array

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d)
print("Dimenstion: ",array_2d.ndim)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimenstion:  2


In [7]:
# Create a 3-dimensional array

array_3d = np.array([[[1, 2],  [3, 4]], 
                     [[5, 6],  [7, 8]], 
                     [[9, 10], [11, 12]]])

print(array_3d)
print("Dimenstion: ",array_3d.ndim)



[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimenstion:  3


# Important Properties And Attributes of Numpy

In [ ]:
# Shape
# to check shape of an array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.shape)


arr1 = np.array([1, 2, 3])
arr1.shape

In [ ]:
# ndim
# to check dimesnion of an array

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.ndim)



In [3]:
# size
# to check the size
import numpy as np

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.size)


9


In [4]:
# itemsize
# to know the memory size of an array

print(array_2d.itemsize)


4


In [5]:
# dtype
# to know the type of an array

print(array_2d.dtype)


int32


In [7]:
# astype
# type casting in array
# if you want change the data type

array_2d = array_2d.astype('float')

print(array_2d)
array_2d.dtype

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


dtype('float64')

# Functions in Numpy

In [8]:
# zeros
# create one Dimenstion Arrays


arr_zeros = np.zeros((10))
print(arr_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# zeros 
# create n-Dimenstion Arrays

arr_zeros = np.zeros((2, 5,))

print(arr_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# Ones 
# create one Dimenstion Arrays

arr_ones = np.ones((5))
print(arr_ones)


[1. 1. 1. 1. 1.]


In [12]:
# Ones 
# create n-Dimenstion Arrays

arr_ones = np.ones((2,3))
print(arr_ones)


[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# eye
identity_matrix = np.eye(4)
print(identity_matrix)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# eye
identity_matrix = np.eye(3,2)
print(identity_matrix)


[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [23]:
# diag
diagonalArray = np.diag([2,3,5,2,5,6,7])
diagonalArray

array([[2, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [36]:
# generate random Numbers
np.random.randint(1,10)

4

In [38]:
# generate random Numbers
np.random.randint(1,10,6)

array([4, 7, 4, 9, 3, 3])

In [40]:
# Create a range of values
arr_range = np.arange(0, 10)
print(arr_range)



[0 1 2 3 4 5 6 7 8 9]


In [46]:
# Create a range of values
arr_range = np.arange(0,11,5)
print(arr_range)



[ 0  5 10]


In [47]:
# Create an array with evenly spaced values
arr_linspace = np.linspace(1, 4, 4)
print(arr_linspace)

[1. 2. 3. 4.]


# Indexing and slicing


In [56]:

array_1d = np.array([8, 9, 10, 11, 12])
#index               0  1   2  3  4
array_1d[0:2]

array([8, 9])

# Iterating over Numpy

In [2]:
import numpy as np


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Iterate over each element in the array
for i in arr:
    print(i)
    
arr.T

[1 2 3]
[4 5 6]
[7 8 9]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [3]:
# Iterate over each column

for i in arr.T:
    print(i)

[1 4 7]
[2 5 8]
[3 6 9]


In [4]:
# Iterate over each element using np.nditer()
for element in np.nditer(arr):
    print(element)


1
2
3
4
5
6
7
8
9


In [7]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Iterate over each element in the array
for row in arr:
    for element in row:
        print(element)
    print()


1
2
3

4
5
6

7
8
9



# Operations in Array

In [10]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,15])



In [11]:
# substraction
arr1-arr2

array([-3, -3, -3, -3, -3, -9])

In [12]:
# Addition
arr1+arr2

array([ 5,  7,  9, 11, 13, 21])

In [13]:
# Multipication
arr1*arr2

array([ 4, 10, 18, 28, 40, 90])

In [14]:
# Division
arr1/arr2

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.4       ])

In [18]:
# Comparision

arr1 = np.array([1,2,3,4,5,6])

arr1<3

array([ True,  True, False, False, False, False])

In [19]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


In [23]:
# max 
# 0 = row
# 1 = column


print(array_2d.max())
print(array_2d.max(axis=0))
print(array_2d.max(axis=1))




9
[7 8 9]
[3 6 9]


In [25]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

print(array_2d.min())

print(array_2d.min(axis=0))

print(array_2d.min(axis=1))


1
[1 2 3]
[1 4 7]


In [30]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.mean())
print(array_2d.mean(axis=0))
print(array_2d.mean(axis=1))





5.0
[4. 5. 6.]
[2. 5. 8.]


In [31]:

print(array_2d.std())
print(array_2d.std(axis=0))
print(array_2d.std(axis=1))


2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [32]:

print(np.median(array_2d))
print(np.median(array_2d,axis=0))
print(np.median(array_2d,axis=1))


5.0
[4. 5. 6.]
[2. 5. 8.]


# Deep Dive Reshaping

In [40]:
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

newArray = arr_1d.reshape(5, 5)
newArray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [38]:
newArray = arr_1d.reshape(5, 2)
newArray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

newArray = arr_1d.reshape(3, 3)
newArray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr1 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])


In [44]:
# ravel : to change the shape of an array from n dimesion to 1D 


arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# transpose : changing row to Column and Column to Row 
arr1.transpose()


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
# stacking : combining two different array to one array
# hstack 

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])


np.hstack((arr1,arr2))


array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9])

In [48]:
# vstack
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
arr3 = np.array([4,5,6,7,8,9])
arr4 = np.array([4,5,6,7,8,9])
arr5 = np.array([4,5,6,7,8,9])


np.vstack((arr1,arr2,arr3,arr4,arr5))


array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9]])

In [54]:
# splitting an array
# hsplit

arr1 = np.array([1,2,3,4,5,6,7,8])

np.hsplit(arr1,2)


[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [56]:
# splitting an array
# vsplit
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

np.vsplit(array_2d,3)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]