In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = [1, 2, 3, 4, 5]




# Standadize
# Normalize

In [21]:
# Standadize

import numpy as np
from sklearn.preprocessing import StandardScaler

data = [1, 2, 3, 4, 5,1000]

data = np.array(data).reshape(-1, 1)  # Reshape to 2D array

print(data)

scaler = StandardScaler()
print(scaler)
scaled_data = scaler.fit_transform(data)
print(scaled_data)



[[   1]
 [   2]
 [   3]
 [   4]
 [   5]
 [1000]]
StandardScaler()
[[-0.45259357]
 [-0.44990224]
 [-0.4472109 ]
 [-0.44451956]
 [-0.44182822]
 [ 2.23605448]]


In [20]:
# Normalize
import numpy as np
from sklearn.preprocessing import MinMaxScaler
data = [10,20,30,45,55,61,70,80,91,1001]

data = np.array(data).reshape(-1, 1)  # Reshape to 2D array (5x1)
print(data)

minScaler = MinMaxScaler()
scaled_data = minScaler.fit_transform(data)

print(scaled_data)


[[  10]
 [  20]
 [  30]
 [  45]
 [  55]
 [  61]
 [  70]
 [  80]
 [  91]
 [1001]]
[[0.        ]
 [0.01009082]
 [0.02018163]
 [0.03531786]
 [0.04540868]
 [0.05146317]
 [0.0605449 ]
 [0.07063572]
 [0.08173562]
 [1.        ]]
