In [2]:
# Create a 1-dimensional array
import numpy as np

oneDarray = np.array([1,2,3])

oneDarray

print(oneDarray.ndim)


1


In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])

print(array_1d)
print("Dimenstion: ",array_1d.ndim)


In [ ]:
# Create a 2-dimensional array

array_2d = np.array([[1, 2, 3], 
                     [7, 8, 9]])


print(array_2d)
print("Dimenstion: ",array_2d.ndim)



In [3]:
# Create a 3-dimensional array

array_3d = np.array([[[1, 2],  [3, 4]], 
                     [[5, 6],  [7, 8]], 
                     [[9, 10], [11, 12]]])

print(array_3d)
print("Dimenstion: ",array_3d.ndim)



[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimenstion:  3


# Important Properties And Attributes of Numpy

In [5]:
# Shape
# to check shape of an array
array_2d = np.array([[1, 2, 3,4], 
                     [4, 5, 6,4], 
                     [7, 8, 9,10]])


print(array_2d.shape)




(3, 4)


In [6]:
arr1 = np.array([1, 2, 3])
arr1.shape


(3,)

In [7]:
# ndim
# to check dimesnion of an array

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.ndim)



2


In [10]:
# size
# to check the size
import numpy as np

array_2d = np.array([[1, 2, 3,6], 
                     [4, 5, 6,8], 
                     [7, 8, 9,9]])


print(array_2d.size)


12


In [11]:
# dtype
# to know the type of an array

array_2d.dtype


dtype('int32')

In [17]:
# astype
# type casting in array
# if you want change the data type

array_2d = np.array([[1, 2, 3,6], 
                     [4, 5, 6,8], 
                     [7, 8, 9,9]])

print(array_2d.dtype)

array_2d = array_2d.astype('float')

print(array_2d.dtype)

array_2d = array_2d.astype('int')

array_2d.dtype

int32
float64


dtype('int32')

# Functions in Numpy

In [19]:
# zeros
# create one Dimenstion Arrays


np.zeros((5))


array([0., 0., 0., 0., 0.])

In [29]:
# zeros 
# create n-Dimenstion Arrays

abc = np.zeros((3,4))
print(abc.ndim)
print(abc)


2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
# Ones 
# create one Dimenstion Arrays

arr_ones = np.ones((2,5))
print(arr_ones.ndim)
print()
print(arr_ones)


2

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
# Ones 
# create n-Dimenstion Arrays

arr_ones = np.ones((2,3))
print(arr_ones)


[[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
# eye
identity_matrix = np.eye(4)
print(identity_matrix.ndim)
print(identity_matrix)



2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
# eye
identity_matrix = np.eye(4,7)
print(identity_matrix)


[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [50]:
# diag
diagonalArray = np.diag([2,3,4,5])
diagonalArray


array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [74]:
# generate random Numbers
np.random.randint(1,10)



8

In [93]:
# generate random Numbers
np.random.randint(1,10,3)


array([4, 2, 7])

In [94]:
# Create a range of values
arr_range = np.arange(0, 10)
print(arr_range)



[0 1 2 3 4 5 6 7 8 9]


In [102]:
# Create a range of values
arr_range = np.arange(0,11,2)
print(arr_range)


[ 0  2  4  6  8 10]


In [111]:
# Create an array with evenly spaced values
arr_linspace = np.linspace(1, 101, 5)
print(arr_linspace)


[  1.  26.  51.  76. 101.]


# Indexing and slicing


In [113]:

array_1d = np.array([8, 9, 10, 11, 12])
#index               0  1   2  3  4
array_1d[0:5]


array([ 8,  9, 10, 11, 12])

# Iterating over Numpy

In [114]:
import numpy as np


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Iterate over each element in the array
for i in arr:
    print(i)
    


[1 2 3]
[4 5 6]
[7 8 9]


In [115]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [116]:
# Iterate over each column

for i in arr.T:
    print(i)
    

[1 4 7]
[2 5 8]
[3 6 9]


array(1)

In [124]:
# Iterate over each element using np.nditer()
for element in np.nditer(arr):
    print(element)


1
2
3
4
5
6
7
8
9


In [125]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Iterate over each element in the array
for row in arr:
    for element in row:
        print(element)
    print()


1
2
3

4
5
6

7
8
9



# Operations in Array

In [127]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,15])
print(arr1)
print(arr2)


[1 2 3 4 5 6]
[ 4  5  6  7  8 15]


In [131]:
# substraction
print(arr2)

print(arr1)

print(arr2-arr1)


[ 4  5  6  7  8 15]
[1 2 3 4 5 6]
[3 3 3 3 3 9]


In [132]:
# Addition
arr1+arr2


array([ 5,  7,  9, 11, 13, 21])

In [ ]:
# Multipication
arr1*arr2


In [133]:
# Division
arr1/arr2


array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.4       ])

In [140]:
# Comparision

arr1 = np.array([1,2,3,4,5,6])
print(arr1)

3<=arr1


[1 2 3 4 5 6]


array([False, False,  True,  True,  True,  True])

In [142]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


In [146]:
# max 
# 0 = row
# 1 = column


array_2d.max()

print(array_2d.max(axis=0))
print(array_2d.max(axis=1))



[3 6 9]


In [147]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

print(array_2d.min())

print(array_2d.min(axis=0))

print(array_2d.min(axis=1))


1
[1 2 3]
[1 4 7]


In [ ]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.mean())
print(array_2d.mean(axis=0))
print(array_2d.mean(axis=1))




In [ ]:

print(array_2d.std())
print(array_2d.std(axis=0))
print(array_2d.std(axis=1))


In [ ]:

print(np.median(array_2d))
print(np.median(array_2d,axis=0))
print(np.median(array_2d,axis=1))


# Deep Dive Reshaping

In [157]:
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8,9])

arr_1d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
newArray = arr_1d.reshape(2, 5)
newArray


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [159]:
newArray = arr_1d.reshape(5, 2)
newArray


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [160]:
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

newArray = arr_1d.reshape(3, 3)
newArray


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [162]:
arr1 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
# ravel : to change the shape of an array from n dimesion to 1D 

arr1.ravel()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
arr1 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
# transpose : changing row to Column and Column to Row 
arr1.transpose()


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [166]:
# stacking : combining two different array to one array
# hstack 

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])


np.hstack((arr1,arr2))


array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9])

In [169]:
# vstack
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
arr3 = np.array([4,5,6,7,8,9])
arr4 = np.array([4,5,6,7,8,9])
arr5 = np.array([4,5,6,7,8,9])


np.vstack((arr1,arr2,arr3,arr4,arr5))


array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9]])

In [172]:
# splitting an array
# hsplit

arr1 = np.array([1,2,3,4,5,6,7,8])

np.hsplit(arr1,2)


[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [173]:
# splitting an array
# vsplit
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

np.vsplit(array_2d,3)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]